##########################################################
#                                                        #
#                   G4Gun Standard Macro                 #
#                                                        #
##########################################################
#PreInit:

#  Define the level of verbosity of messages
# options: debugging, development, trace, routine, warning, error
# default: routine
#/ds/manager/log trace
/ds/manager/log routine
/ds/manager/verbosity 5
/ds/manager/checkoverlap 0
/ds/manager/eventcounter 1000
/ds/manager/writephotons 0
/ds/manager/writedeposits 1
/ds/manager/writedaughters 1

#Define if geometry has to be exported in GDML file geo.root
#/ds/manager/GDML 0

#Detector configuration: TPC+NW+WT (0) - TPC+NW (1) - TPC (2) -TPC+NW+SourceHolder+WT(10)
/ds/detector/configuration ds50_full

# Define output file name
/run/filename outamc

# Define  random seed
/run/heprandomseed 123421036

#Define the hadronic physics list (none QGSP_BERT_HP QGSP_BIC_HP FTF_BIC_HP FTFP_BERT_HP)
/ds/physics/hadronic_list HP
#/ds/physics/hadronic_list QGSP_BERT_HP

#Define the EM physics list (standard livermore)
/ds/physics/em_list livermore

/ds/physics/optics 0
/ds/physics/killS1S2 1

#-----------------------------------
/run/initialize
#-----------------------------------

#PostInit:

#simulates the neutron spectrum of the gamma-less AmC source
#please note that the 60 keV gammas from the 241Am are not simulated/ considered in this generator.
/ds/generator/select AmCSource

#the neutron energy correlates with the angle of emission because of the alpha kinetic energy being angle dependent. Therefore there is a direction dependency.
/ds/generator/AmC/energyanglecorrelationfile ../data/physics/amc1umFoil_out_thetaNVsEnH.txt
#along -y axis, default rotation: 0 0 1
#/ds/generator/AmC/rotation 0 -1 0

#default position: 0 0 0 cm
/ds/generator/sphere_radius 1 mm
/ds/generator/set_center 0. 32. 0. cm
#/ds/generator/direction 0 -1 0 #the direction command is overwritten by the AmC sources energy-direction correlation, use the source's rotation command above to re-direct the source.

# Define the number of events
/run/beamOn 10000
