##########################################################
#                                                        #
#                   G4Gun Standard Macro                 #
#                                                        #
##########################################################


#PreInit:

#  Define the level of verbosity of messages
# options: debugging, development, trace, routine, warning, error
# default: routine
#/ds/manager/log trace
/ds/manager/log routine
/ds/manager/verbosity 1
/ds/manager/checkoverlap 0
/ds/manager/eventcounter 100


# Detector configurations:
# ds50_full ds50_tpc_veto ds50_tpc ds20k ds20k_tpc dsproto dsproto0 red_tpc dart ardm tester

/ds/detector/configuration ds20k


# Define output file name
/run/filename outbias

# Define  random seed
/run/heprandomseed 12345679



#Define the hadronic physics list (none QGSP_BERT_HP QGSP_BIC_HP FTF_BIC_HP FTFP_BERT_HP)
/ds/physics/hadronic_list QGSP_BERT_HP

#Define the EM physics list (standard livermore)
/ds/physics/em_list livermore
/ds/physics/killS1S2 1
/ds/detector/vetoyieldfactor 0.0


#/ds/bias/type Sphere
#/ds/bias/radius 1 m
#/ds/bias/side 1 m
#/ds/bias/half_z 1 m
#/ds/bias/center 0 0 0 m


#-----------------------------------
/run/initialize
#-----------------------------------


#PostInit:

/ds/generator/select Bias

# skip first N events 
# /ds/generator/bias/skip_events 100

# amplify (i.e. repeat the same event) by N times 
/ds/generator/bias/amplification 10

# smear direction in degrees
/ds/generator/bias/smear_direction 0.1

# smear energy in percentage 
/ds/generator/bias/smear_energy 0.1

# do not track events if energy is below the threshold 
#/ds/generator/bias/minimum_energy 500 keV

# input file 
/ds/generator/bias/file outneutrons.fil

/ds/stack/select NeutronCapture



# Define the number of events
/run/beamOn 10000
