##########################################################
#                                                        #
#                   G4Gun Standard Macro                 #
#                                                        #
##########################################################


#PreInit:

#  Define the level of verbosity of messages
# options: debugging, development, trace, routine, warning, error
# default: routine
/ds/manager/log trace
/ds/manager/verbosity -1
/ds/manager/checkoverlap 0
/ds/manager/eventcounter 100
/ds/manager/writephotons 0
/ds/manager/writedeposits 1
/ds/manager/writedaughters 0
/ds/manager/checkoverlap 0


#Detector configuration: TPC+NV+WT (0) - TPC+NW (1) - TPC (2) - NV+WT (3) - Tester (4) - TPC_DS10 (5)
/ds/detector/configuration ds50_full

#/ds/detector/scintillator GdScintillator


# Define output file name
/run/filename outdev

# Define  random seed
/run/heprandomseed 12345679

#Define the hadronic physics list (none HP Shielding QGSP_BERT_HP QGSP_BIC_HP FTF_BIC_HP FTFP_BERT_HP)
/ds/physics/hadronic_list none

#Define the EM physics list (standard livermore)
/ds/physics/em_list livermore

#Define the LAr scintillation model: No scintillation (0) - NEST (1) - DSLight (2)
/ds/physics/optics 0
#/ds/physics/killS1S2 1
#/ds/physics/killS2 0
#/ds/physics/scaleS2 3
#/ds/physics/DriftField 1 kV/cm
#/ds/physics/ExtractionField 2.8 kV/cm

#-----------------------------------
/run/initialize
#-----------------------------------

#PostInit:


/ds/generator/select G4Gun

/ds/generator/particle  e-
#/ds/generator/energyfile spectrum.dat
/ds/generator/energy    100. keV
#/ds/generator/position  0 0 0 cm
#/ds/generator/direction 5.0 2.0  -1.0

/ds/generator/tpcdistribution 1
# Define the number of events
/run/beamOn 10
