##########################################################
#                                                        #
#            DS20K FLUKA output Simulation               #
#                                                        #
##########################################################


#PreInit:

#  Define the level of verbosity of messages
# options: debugging, development, trace, routine, warning, error
# default: routine
/ds/manager/log routine
/ds/manager/verbosity 0
/ds/manager/checkoverlap 0
/ds/manager/eventcounter 500
/ds/manager/writephotons 0
/ds/manager/writedeposits 1
/ds/manager/writedaughters 0

#Define if geometry has to be exported in GDML file geo.root
/ds/manager/GDML 0

#  Detector configuration:
#  DS50  TPC+NV+WT (0) - DS50 TPC+NW (1) - DS50 TPC (2) - DS50 NV+WT (3)
#  LAr Tester (4) -  DS10 TPC (5) -  Scintillator tester (6)
#  DSG2 TPC + NV + WT (7) - DSG3 TPC + NV (8) - DS5k TPC (9)
#  DS20k TPC + WT (10)


/ds/detector/configuration ds20k

/ds/detector/ExtLarScintillating 0
/ds/detector/vetoyieldfactor 0.0

# Define output file name
/run/filename outFluka

# Define  random seed
/run/heprandomseed 1276

#Define the hadronic physics list (none QGSP_BERT_HP QGSP_BIC_HP FTF_BIC_HP FTFP_BERT_HP)
/ds/physics/hadronic_list none

#Define the EM physics list (standard livermore)
/ds/physics/em_list livermore

/ds/physics/optics 3

/ds/physics/tuned200V   1
/ds/physics/killS1S2 1


#-----------------------------------
/run/initialize
#-----------------------------------

#PostInit:


#set the fluka filename (before building the generator), otherwise use ../data/physics/fluka_output_example.dat
/ds/generator/fluka_filename test1.dat
#build the FLUKA generator. No other command is required
/ds/generator/select FLUKA

# Define the number of events
/run/beamOn 10
